# Generated by Django 3.1.7 on 2021-03-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_post_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='삭제여부'),
        ),
    ]
