# Generated by Django 3.1.7 on 2021-03-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_post_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True, verbose_name='게시판 별명'),
        ),
    ]
